name: deploy-book
on:
  push:
    branches: [ main ]   # change to 'master' if that's your default branch

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -U jupyter-book
      # If your book root is the REPO ROOT (has _config.yml and _toc.yml):
      - run: jupyter-book build .
      # If your book is in a subfolder (e.g., mynewbook), replace with:
      # - run: jupyter-book build mynewbook
      - uses: actions/upload-pages-artifact@v3
        with:
          path: _build/html
          # If you built a subfolder, use: path: mynewbook/_build/html

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4